apiVersion: v1
kind: Secret
metadata:
  name: car-crash-secret
  namespace: default
type: Opaque
stringData:
  SOCRATA_TOKEN: ${SOCRATA_APP_TOKEN}
  S3_ACCESS_KEY: ${S3_ACCESS_KEY}
  S3_SECRET_KEY: ${S3_SECRET_KEY}
  ICEBERG_PATH: ${ICEBERG_PATH}
  RAW_DATA_PATH: ${RAW_DATA_PATH}