apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-operator-event-binding
  namespace: spark-operator
subjects:
  - kind: ServiceAccount
    name: spark-operator-controller
    namespace: spark-operator
roleRef:
  kind: Role
  name: spark-operator-event-writer
  apiGroup: rbac.authorization.k8s.io