apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-operator-event-writer
  namespace: spark-operator
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch", "update"]