name: Destroy Infra

on:
  workflow_dispatch:
    inputs:
      stack_name:
        description: 'stack name ?'
        required: true
        default: 'prod'
env:
  K8S_BOOTUP_TIME_SEC: 180
  DAG_RUN_TIME_SEC: 900
  DAG_NAME: chicago_car_crash_pipeline
jobs:
  destioy_infra:
    runs-on: ubuntu-latest
    environment: cicd
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.14.0

      - name: 🦭Install kubeseal
        uses: digitalservicebund/setup-kubeseal@v1.0.0

      - name: Install envsubst
        run: sudo apt-get update && sudo apt-get install -y gettext

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_TOKEN }}

      - name: 🐍Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          cd infra-as-code
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Pulumi CLI
        uses: pulumi/actions@v4
        with:
          pulumi-version: latest

      - name: Login to Pulumi
        run: pulumi login
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      - name: 💥tear down all resources
        run: |
          export PULUMI_STACK_NAME=${{ github.event.inputs.stack_name }}
          pulumi config set digitalocean:token ${{ secrets.DO_TOKEN }} --secret
          pulumi refresh --yes
          cd infra-as-code
          pulumi stack select $PULUMI_STACK_NAME
          export K8S_CLUSTER_ID=$(pulumi stack output k8s_cluster_id)
          doctl kubernetes cluster kubeconfig save $K8S_CLUSTER_ID
          echo "Deleting airflow load balancer service..."
          kubectl -n airflow delete svc airflow-lb --ignore-not-found
          helm uninstall spark-operator -n spark-operator --ignore-not-found
          helm uninstall airflow -n airflow --ignore-not-found
          kubectl delete all --all  --wait=true --timeout=0s
          sleep 180
          kubectl delete pvc --all
          kubectl delete secrets --all
          kubectl delete configmaps --all
          echo "Deleting K8S cluster..."
          pulumi destroy --remove --yes
          echo "Deleting orphan pvc volumes in cloud..."
          echo "list of orphans...."
          doctl compute volume list --format ID,Name,DropletIDs | awk '$3 == "" && $2 ~ /^pvc-/'
          echo "Deleting orphan volumes..."
          doctl compute volume list --format ID,Name,DropletIDs --no-header | awk '$3 == "" && $2 ~ /^pvc-/ { print $1 }' | xargs -n1 -I {} doctl compute volume delete {} --force
          echo "Deleting other volumes..."
          sleep 300
          doctl compute volume list --format ID,Name,DropletIDs | awk '$3 != "[]" && $2 ~ /^pvc-/'
          doctl compute volume list --format ID,Name,DropletIDs --no-header | awk '$3 != "[]" && $2 ~ /^pvc-/ { print $1 }' | xargs -n1 -I {} doctl compute volume delete {} --force