name: Deploy to DigitalOcean Kubernetes

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DO_TOKEN: ${{ secrets.DO_TOKEN }}
      CLUSTER_NAME: k8s-1-33-1-do-1-sgp1-1752378431833
      REGION: sgp1
      VERSION: 1.33.1-do.1
      PROJECT_NAME: first-project
      POOL_NAME: pool-l7g14a0wb
      NODE_COUNT: 3
      TAGS: '["testing", "k8s"]'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install doctl
        run: |
          curl -sL https://github.com/digitalocean/doctl/releases/latest/download/doctl-linux-amd64.tar.gz | tar -xz
          sudo mv doctl /usr/local/bin

      - name: Authenticate with DigitalOcean
        run: doctl auth init -t $DO_TOKEN

      - name: Check if Kubernetes cluster exists
        id: check_cluster
        run: |
          if doctl kubernetes cluster get "$CLUSTER_NAME" > /dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Kubernetes cluster if not exists
        if: steps.check_cluster.outputs.exists == 'false'
        run: |
          doctl kubernetes cluster create "$CLUSTER_NAME" \
            --version "$VERSION" \
            --region "$REGION" \
            --tag "$TAGS" \
            --project "$PROJECT_NAME" \
            --node-pool "name=$POOL_NAME;size=s-2vcpu-4gb;count=$NODE_COUNT"

      - name: Set kubeconfig
        run: doctl kubernetes cluster kubeconfig save "$CLUSTER_NAME"

      - name: Verify cluster nodes
        run: kubectl get nodes
